site_name: Amba Event Stream
site_description: 'documentation for amba event stream'
site_author: 'Lukas Jesche'
docs_dir: docs/
repo_name: 'ambalytics/amba-event-stream'
repo_url: 'https://github.com/ambalytics/amba-event-streame'
nav:
    - Home: index.md
    - Code Reference:
      - Workflow: code_ref.md

theme:
  name: material
  palette:
    scheme: preference
    primary: teal
    accent: purple

plugins:
  - search
  - mkdocstrings
  - gen-files:
      scripts:
        - docs/gen_doc_stubs.py
