site_name: Amba Event Stream
site_description: 'documentation for amba event stream'
site_author: 'Lukas Jesche'
docs_dir: docs/
repo_name: 'ambalytics/amba-event-stream'
repo_url: 'https://github.com/ambalytics/amba-event-stream'
nav:
    - Home: index.md
    - Code Reference:
      - event: event_ref.md
      - event stream base: event_stream_base_ref.md
      - event stream consumer: event_stream_consumer_ref.md
      - event stream producer: event_stream_producer_ref.md

theme:
  name: material
  palette:
    scheme: preference
    primary: teal
    accent: purple

plugins:
  - search
  - mkdocstrings
