name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main

jobs:
    build-and-deploy:
      name: Deploy docs
      runs-on: ubuntu-latest
      steps:
        - name: Checkout master
          uses: actions/checkout@v2.3.1

        - name: Set up Python 3.8
          uses: actions/setup-python@v1
          with:
            python-version: 3.8

        - name: Install dependencies
          run: pip install . -r docs/requirements.txt

        - name: reset
          run: git checkout --orphan gh-pages
               git rm -rf .
               git commit --allow-empty -m "Initializing gh-pages branch"

        - name: deploy
          run: mkdocs gh-deploy