name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main

jobs:
    build-and-deploy:
      name: Deploy docs
      runs-on: ubuntu-latest
      steps:
        - name: Checkout master
          uses: actions/checkout@v2.3.1

        - name: deploy
          run: mkdocs gh-deploy